spring:
  datasource:
    url: postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:papi}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      dll-auto: validate